# Making the baseURL empty allows links to work correctly on both
# dev and prod
baseURL = ""
languageCode = "en-us"
title = "mbedded.ninja"
theme = "ananke"
sectionPagesMenu = "main"
pluralizelisttitles = "false"
pygmentsCodeFences = "true"
disqusShortname = "cladlab"