# Making the baseURL empty allows links to work correctly on both
# dev and prod
baseURL = ""
languageCode = "en-us"
title = "mbedded.ninja"
#theme = "ananke"
sectionPagesMenu = "main"
pluralizelisttitles = "false"
pygmentsCodeFences = "true"
disqusShortname = "blog-mbedded-ninja"

[params]
    author = "Geoffrey Hunter"
    description = "An embedded engineering site that's got your back."

[blackfriday]
fractions = false
extensionsmask = ["autolink"] # Prevent naked URL from being converted into links, as this creates problems when the are URLs in figure captions.