# Making the baseURL empty allows links to work correctly on both
# dev and prod
# UPDATE 2019-03-10: Discovered sitemap.xml is incorrect when baseURL is empty,
# recommendation is to set to prod URL
baseURL = "https://blog.mbedded.ninja/"

languageCode = "en-us"
title = "mbedded.ninja"
sectionPagesMenu = "main"
pluralizelisttitles = "false"
pygmentsCodeFences = "true"
disqusShortname = "blog-mbedded-ninja"
googleAnalytics = "UA-92834105-2"

# This preserves the capitilization of tags, which is important for 
# tags such as "CSS", "C++", "GPS", e.t.c.
preserveTaxonomyNames = "true" 

[params]
    author = "Geoffrey Hunter"
    description = "An embedded engineering site that's got your back."    

[blackfriday]
    fractions = false
    extensionsmask = ["autolink"] # Prevent naked URL from being converted into links, as this creates problems when the are URLs in figure captions.

[related]
    threshold= 80
    includeNewer = true
    toLower = false
    [[related.indices]]
        name = "keywords"
        weight = 100
    [[related.indices]]
        name = "tags"
        weight = 100